### ISSUE TITLE
ReferenceError: Can't find variable: Promise

### ISSUE THREAD

**Issue by mfeliu** [kreopt/jinjajs#1]
I get the following error while including **jinjajs** in my Jasmine tests:

```
ReferenceError: Can't find variable: **Promise**
    at .../bower_components/jinjajs/jinja.js:446
```

What implementation of **Promise** are you using? We should specify it in the package files.

**Comment by kreopt** [comment]
It's ES6 Promise. Had not test this with different environments cause this implementation is just for fun at the moment. But if you describe what JS engine are you using, I'll check this issue

**Comment by mfeliu** [comment]
Hi! Thanks for answering. I am using Jasmine executing over PhantomJS and my intention is to use original Django Jinja templates as fixtures for Jasmine tests. Thanks again.

**Comment by kreopt** [comment]
Unfortunately, PhantomJS still lacks native promises API.
You can try use this polyfill: https://github.com/jakearchibald/es6-promise
As I remember, I'd succesfully use it in old browsers with no promise support.

And if you missing some Django-template functionality - just make some new issues. There is no full support of this engine at the moment.

**Comment by mfeliu** [comment]
Thank you!
